### PR TITLE
12533 quorum 202

### PR DESCRIPTION
**Pull request by bdionne**
This requires a fabric branch of the same name

### CODE REVIEW

**Comment by kocolosk** [comment]
LGTM @bdionne.  I reverted your whitespace patch because it was causing a spurious merge conflict with master.  If you agree with my whitespace changes can you squash this all down into a single patch and re-submit?  Also, I think in this case we're pretty decoupled from the `fabric` work.  When it lands, we'll be ready, but it's not like merging this branch is going to break BigCouch in the meantime.

**Comment by bdionne** [comment]
hmm, there was a whitespace before the code commit also. In any event I removed both

**Comment by kocolosk** [comment]
I think we got our signals crossed here.  I was asking you to consider squashing 0b079d4291881b1143c814f5db4847f18204c1c2 into 868e2bd9b00cf7b66528b3c32a6cb5eefb38bafb, but it looks like you threw it away instead.  Can you also rewrite the commit message?  The body doesn't make much sense once the commit is on master.

**Comment by bdionne** [comment]
oh, I see, one of the whitespace fixes was just reformatting code. I think I recovered that and rewrote the message

**Pull request merged**
